#!/bin/bash

# Check if all 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Error transferring the file."
fi
